#!/bin/sh

# Run redaction on our notes and git-add the redacted file.
mv NOTES.md NOTES.md.old
perl -0 -pe 's/{~.*?~}/ [REDACTED] /gs' NOTES.md.old > NOTES.md
git add NOTES.md
mv NOTES.md.old NOTES.md
