#!/bin/sh

# pre-push
# ========
#
# The pre-push hook simply pushes the commits to the wiki whenever a push to the
# repository is made.

echo ">>> [HOOK] pre-push: Start"

# It's time to push the wiki commits!
wikidir=".wiki/"

env -i git -C "$wikidir" push -u origin $(git branch --show-current)

echo "<<< [HOOK] pre-push: End"
